"rentsetting": “Organization settings”
"prosetting": "Project Manage"
# site
# organization
"rentsetting.wiki-management": "Wiki management"
"global.menusetting.icon": "space icon"


# project
"prosetting.wiki-management": "Wiki management"

# user

