"rentsetting": “Organization settings”
"prosetting": "Project Manage"
# site
# organization
"rentsetting.wiki-management": "knowledge management"

# project
"prosetting.wiki-management": "knowledge management"

# user

