"rentsetting": “Organization settings”
"prosetting": "Project Manage"
# site
# organization
"rentsetting.wiki-management": "knowledge management"
"global.menusetting.icon": "space icon"


# project
"prosetting.wiki-management": "knowledge management"

# user

